# Generated by Django 5.2.3 on 2025-07-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_room_address_room_floors_room_phone_room_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Shop.room')),
            ],
        ),
    ]
