# Generated by Django 5.2.3 on 2025-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_room_photo_alter_room_number_roomphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], max_length=6420),
        ),
    ]
