# Generated by Django 5.2.3 on 2025-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_room_price_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/'),
        ),
    ]
